
export interface UserProfile {
  uid: string;
  email: string | null;
  name?: string;
  profileField?: string; // e.g., "Software Engineering", "Product Management"
  role?: string; // e.g., "Frontend Developer", "Senior PM"
  company?: string;
  education?: string;
  phoneNumber?: string;
  // resumeUrl?: string; // Optional resume upload
  createdAt: string;
  interviewsTaken?: number;
  isPlusSubscriber?: boolean;
  isAdmin?: boolean; // For admin role
}

export interface InterviewSession {
  id: string;
  userId: string;
  duration: 15 | 30 | 45; // minutes
  status: "pending" | "questions_generated" | "started" | "completed" | "cancelled";
  questions?: GeneratedQuestion[]; // Questions generated by AI
  transcript?: string; // Full interview transcript
  feedback?: InterviewFeedback;
  createdAt: string;
  updatedAt?: string;
}

export interface GeneratedQuestion {
  id: string;
  text: string;
  stage: "oral" | "technical_written";
  type: "behavioral" | "technical" | "coding" | "conversational";
  answer?: string; // User's answer for this question
  // May include expected answer hints or difficulty
}

export interface InterviewFeedback {
  overallScore?: number; // 0-100
  overallFeedback: string;
  correctAnswersSummary: string;
  incorrectAnswersSummary: string;
  areasForImprovement: string;
  // Could also include detailed feedback per question
}
